# Automatically benchmark commits to Rnm and update the benchmark website
# Performs the following actions:
#   Checkout hyperspy-bench / gh-pages
#   Upload previous results and config file to GH artifact
#   Checkout RELEASE_next_minor
#   Install python, hyperspy and asv
#   Run latest commit
#   Upload new result to GH artifact
#   Download and merge previous results without overwriting
#   Generate website and upload website to GH artifact
#   Checkout hyperspy-bench/gh-pages
#   Add results (overwriting old) and overwrite website
#   Push changes

name: Bench Rnm-push to gh-pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ] # Change to RELEASE_next_minor

defaults:
  run:
    shell: bash -l {0}
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Benchmark_Results: # Name of job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Checkout hyperspy-bench/gh-pages
      uses: actions/checkout@v2
      with:
        repository: thomasaarholt/hyperspy-bench
        ref: gh-pages
        token: ${{ secrets.BENCHMARK_PAT }}

    - name: Upload old results
      uses: actions/upload-artifact@v2
      with:
        name: asv_old_results
        path: results

    - name: Upload configuration file
      uses: actions/upload-artifact@v2
      with:
        name: asv_conf_json
        path: asv.conf.json

    - name: Checkout hyperspy
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: test_env
        environment-file: conda_environment.yml
        python-version: "3.7"

    - name: Install HyperSpy and ASV
      run: |
        conda install pip
        pip install .
        pip install asv
    
    - name: Download ASV config
      uses: actions/download-artifact@v2
      with:
        name: asv_conf_json

    - name: Set ASV config
      run: asv machine --machine generic_name --os test --arch test --cpu test --num_cpu 1 --ram '1GB' 

    - name: Run Benchmarks
      run: asv run --machine generic_name

    - name: Upload new results    
      uses: actions/upload-artifact@v2
      with:
        name: asv_new_results
        path: results

    - name: Download and merge old results
      uses: actions/download-artifact@v2
      with:
        name: asv_old_results
        path: old_results

    # Merge old results into new results without overwriting
    - name: Merge old into new results (without overwriting)
      run: |
        mkdir -p results
        mv -n old_results/*.json ../results/

    - name: Generate html
      run: asv publish

    - name: Upload html
      uses: actions/upload-artifact@v2
      with:
        name: asv_html
        path: html

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout hyperspy-bench / gh-pages
      uses: actions/checkout@v2
      with:
        repository: thomasaarholt/hyperspy-bench
        ref: gh-pages
        token: ${{ secrets.BENCHMARK_PAT }}

    - name: Download new results (overwriting any duplicates)
      uses: actions/download-artifact@v2
      with:
        name: asv_new_results
        path: results

    - name: Download and overwrite html
      uses: actions/download-artifact@v2
      with:
        name: asv_html

    - name: Push changes to gh-pages
      run: |
        git config --global user.email "thomasaarholt@gmail.com"
        git config --global user.name "Thomas Aarholt"
        git add --all
        git commit -m "Added Benchmark Result"
        git push
