# This is a basic workflow to help you get started with Actions

name: Automatic Benchmarking on Commit to gh-pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ] # Change to RELEASE_next_minor

defaults:
  run:
    shell: bash -l {0}
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Checkout hyperspy-bench/gh-pages
      uses: actions/checkout@v2
      with:
        repository: thomasaarholt/hyperspy-bench
        ref: gh-pages
        token: ${{ secrets.BENCHMARK_PAT }}

    - name: Upload old results
      uses: actions/upload-artifact@v2
      with:
        name: asv_old_results
        path: results

    - name: Upload configuration file
      uses: actions/upload-artifact@v2
      with:
        name: asv_conf
        path: asv.conf.json

    - name: Checkout hyperspy
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: test_env
        environment-file: conda_environment.yml
        python-version: "3.7"

    - run: |
        conda info
        conda list
        which python
        which python3
        python -V
        conda install pip
        pip install .[tests]
        pip install asv
    
    - uses: actions/download-artifact@v2
      with:
        name: asv_conf #my-artifact

    - name: setup asv
      run: |

        asv machine --machine generic_name --os test --arch test --cpu test --num_cpu 1 --ram '1GB' 
        #asv run v1.6.0^! --machine generic_name
        #asv run v1.5.2^! --machine generic_name
        #asv run v1.5^! --machine generic_name
        #asv run v1.4.1^! --machine generic_name
        #asv run v1.4^! --machine generic_name
        #asv run v1.3.2^! --machine generic_name
        #asv run v1.3.1^! --machine generic_name
        #asv run v1.2^! --machine generic_name
        #asv run v1.1.0^! --machine generic_name
        
        
        asv run 534812e..b56ee0d --steps 500 --machine generic_name
        
    - uses: actions/upload-artifact@v2
      with:
        name: asv_new_results
        path: results

#    - uses: actions/download-artifact@v2
#      with:
#        name: asv_old_results
#        path: results

    - run: |
        asv publish
    - uses: actions/upload-artifact@v2
      with:
        name: asv_html
        path: html

#     - uses: actions/upload-artifact@v2
#       with:
#         name: my-artifact
#         path: .asv/results/generic_name/*.json

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout 
      uses: actions/checkout@v2
      with:
        repository: thomasaarholt/hyperspy-bench
        ref: gh-pages
        token: ${{ secrets.BENCHMARK_PAT }}

    - uses: actions/download-artifact@v2
      with:
        name: asv_new_results #my-artifact
        path: results

    - uses: actions/download-artifact@v2
      with:
        name: asv_html #my-artifact

    - run: |
        ls -a
        git config --global user.email "thomasaarholt@gmail.com"
        git config --global user.name "Thomas Aarholt"
        git add --all
        git commit -m "Added Benchmark Result"
        git push
