# Benchmark latest commit of PR against upstream repo
# Performs the following actions:
#   Checkout hyperspy-bench / gh-pages
#   Upload previous results and config file to GH artifact
#   Checkout RELEASE_next_minor
#   Install python, hyperspy and asv
#   Run specified range of commits with steps between them (see below)
#   Upload new results to GH artifact
#   Download and merge previous results without overwriting
#   Generate website and upload website to GH artifact
#   Checkout hyperspy-bench/gh-pages
#   Add results (overwriting old) and overwrite website
#   Push changes

name: Benchmark PR against Upstream

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
#on: workflow_dispatch
defaults:
  run:
    shell: bash -l {0}
    
on:
  pull_request:
    branches: [ master ] # Should become RELEASE_next_minor
    types: [opened, synchronize, reopened]
    paths: '**.py' # Only trigger when changing python files

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # get all branches and tags

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -V
        conda install pip
        pip install .[tests]
        pip install asv
    
    - name: setup asv
      run: |
        asv machine --yes
        
    - name: Run 
      run: |
        # Get IDs of PR and branch commits
        BRANCH_COMMIT_ID=$(git rev-parse origin/master)
        echo BRANCH_COMMIT_ID
        asv run $BRANCH_COMMIT_ID^! # upstream/RELEASE_next_minor
        
        HEAD_COMMIT_ID=$(git rev-parse HEAD)
        echo $HEAD_COMMIT_ID
        asv run $HEAD_COMMIT_ID^!
    - name: Compare Benchmarks
      run: |
        asv compare $BRANCH_COMMIT_ID^! $HEAD_COMMIT_ID^!
