# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: workflow_dispatch
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]
jobs:
  manual_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.6.0      
    - name: Install dependencies
      run: |
        echo installing...
        pip install .[tests]
        pip install asv
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        asv quickstart --top-level
        echo hi
        asv machine --yes
        echo hello
        echo $GITHUB_HEAD_REF
        asv run HEAD^!
        asv run $GITHUB_HEAD_REF^!
        asv compare $GITHUB_HEAD_REF^! HEAD^!
        echo Finished!
