name: Upload the artifact
on:
  push:
    branches:
      - master

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: Test out the action in this repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      ... do the benchmarking ...

      - name: Upload the file
        uses: actions/upload-artifact@v2
        with:
          name: benchmark_results
          path: output.json
